In [1]:
!pip install numpy


In [2]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# Calculate the mean
mean_value = np.mean(arr)
print("Mean:", mean_value)

# Add 10 to every element (vectorized operation)
arr_plus_10 = arr + 10
print("Array + 10:", arr_plus_10)


Array: [1 2 3 4 5]
Mean: 3.0
Array + 10: [11 12 13 14 15]


In [3]:
import numpy as np

salaries = [
    68000, 72000, 75000, 80000, 85000, 87000, 90000, 95000, 98000, 100000,
    102000, 105000, 110000, 115000, 118000, 120000, 125000, 130000, 135000, 140000,
    142000, 145000, 150000, 155000, 160000, 165000, 170000, 175000, 180000, 185000,
    190000, 195000, 200000, 210000, 220000, 230000, 240000, 250000, 260000, 270000,
    280000, 290000, 300000, 320000, 340000, 360000, 380000, 400000, 420000, 450000
]

salaries_np = np.array(salaries)

mean_salary = np.mean(salaries_np)
median_salary = np.median(salaries_np)
std_dev_salary = np.std(salaries_np)
above_median_count = np.sum(salaries_np > median_salary)

print("Mean salary:", mean_salary)
print("Median salary:", median_salary)
print("Standard deviation:", std_dev_salary)
print("Number of salaries above median:", above_median_count)


Mean salary: 189640.0
Median salary: 162500.0
Standard deviation: 99078.90996574397
Number of salaries above median: 25


In [4]:
import numpy as np


salaries = np.array([
    68000, 72000, 75000, 80000, 85000, 87000, 90000, 95000, 98000, 100000,
    102000, 105000, 110000, 115000, 118000, 120000, 125000, 130000, 135000, 140000,
    142000, 145000, 150000, 155000, 160000, 165000, 170000, 175000, 180000, 185000,
    190000, 195000, 200000, 210000, 220000, 230000, 240000, 250000, 260000, 270000,
    280000, 290000, 300000, 320000, 340000, 360000, 380000, 400000, 420000, 450000
])

np.random.seed(0)
experience_levels = np.random.choice(
    ['EN', 'MD', 'SE'],
    size=len(salaries),
    p=[0.4, 0.4, 0.2]
)

senior_mask = experience_levels == 'SE'
entry_mask = experience_levels == 'EN'

senior_salaries = salaries[senior_mask]
entry_salaries = salaries[entry_mask]

avg_senior_salary = np.mean(senior_salaries)
avg_entry_salary = np.mean(entry_salaries)

percent_senior = (np.sum(senior_mask) / len(salaries)) * 100

print(f"Senior Salaries ({len(senior_salaries)} employees): {senior_salaries}")
print(f"Average Senior Salary: ${avg_senior_salary:,.2f}")
print(f"Average Entry-level Salary: ${avg_entry_salary:,.2f}")
print(f"Percentage of Senior Employees: {percent_senior:.2f}%")


Senior Salaries (8 employees): [ 95000  98000 115000 130000 140000 142000 175000 260000]
Average Senior Salary: $144,375.00
Average Entry-level Salary: $246,642.86
Percentage of Senior Employees: 16.00%


In [1]:
import numpy as np

work_year = np.array([
    2020, 2020, 2021, 2021, 2021, 2022, 2022, 2022, 2023, 2023, 
    2023, 2023, 2024, 2024, 2024, 2024, 2024, 2025, 2025, 2025
])

salary_in_usd = np.array([
    70000, 80000, 75000, 77000, 85000, 90000, 95000, 97000, 100000, 
    105000, 110000, 115000, 120000, 125000, 130000, 135000, 140000, 
    145000, 150000, 155000
])

unique_years = np.unique(work_year)
mean_salaries = []

for year in unique_years:
    mean_salary = np.mean(salary_in_usd[work_year == year])
    mean_salaries.append(mean_salary)

mean_salaries = np.array(mean_salaries)

result = np.column_stack((unique_years, mean_salaries))

for year, salary in result:
    print(f"Year: {int(year)} | Mean Salary: ${int(salary):,}")


Year: 2020 | Mean Salary: $75,000
Year: 2021 | Mean Salary: $79,000
Year: 2022 | Mean Salary: $94,000
Year: 2023 | Mean Salary: $107,500
Year: 2024 | Mean Salary: $130,000
Year: 2025 | Mean Salary: $150,000


In [2]:
import numpy as np
import pandas as pd

salary_in_usd = np.array([
    70000, 80000, 75000, 77000, 85000, 90000, 95000, 97000, 100000, 
    105000, 110000, 115000, 120000, 125000, 130000, 135000, 140000, 
    145000, 150000, 155000
])

company_size = np.array([
    'S', 'M', 'L', 'L', 'M', 'S', 'S', 'M', 'L', 'L',
    'S', 'M', 'L', 'L', 'S', 'S', 'M', 'L', 'M', 'S'
])

salaries_S = salary_in_usd[company_size == 'S']
salaries_M = salary_in_usd[company_size == 'M']
salaries_L = salary_in_usd[company_size == 'L']

def describe(data):
    return {
        "mean": np.mean(data),
        "median": np.median(data),
        "std": np.std(data),
        "min": np.min(data),
        "max": np.max(data)
    }

stats_S = describe(salaries_S)
stats_M = describe(salaries_M)
stats_L = describe(salaries_L)

print("Small Company Stats:", stats_S)
print("Medium Company Stats:", stats_M)
print("Large Company Stats:", stats_L)

variances = {
    'S': np.var(salaries_S),
    'M': np.var(salaries_M),
    'L': np.var(salaries_L)
}

max_variance_size = max(variances, key=variances.get)
print("\nCompany size with highest salary variance:", max_variance_size)

percentiles_S = np.percentile(salaries_S, [25, 50, 75])
percentiles_M = np.percentile(salaries_M, [25, 50, 75])
percentiles_L = np.percentile(salaries_L, [25, 50, 75])

percentile_array = np.array([percentiles_S, percentiles_M, percentiles_L])

print("\nPercentiles (rows = S, M, L | cols = 25th, 50th, 75th):\n", percentile_array)

percentile_df = pd.DataFrame(
    percentile_array,
    index=["Small", "Medium", "Large"],
    columns=["25th", "50th", "75th"]
)
print("\nPretty Percentile Table:\n")
display(percentile_df)


Small Company Stats: {'mean': 112142.85714285714, 'median': 110000.0, 'std': 27367.491515240024, 'min': 70000, 'max': 155000}
Medium Company Stats: {'mean': 111166.66666666667, 'median': 106000.0, 'std': 26491.61292853939, 'min': 80000, 'max': 150000}
Large Company Stats: {'mean': 106714.28571428571, 'median': 105000.0, 'std': 23644.475559626946, 'min': 75000, 'max': 145000}

Company size with highest salary variance: S

Percentiles (rows = S, M, L | cols = 25th, 50th, 75th):
 [[ 92500. 110000. 132500.]
 [ 88000. 106000. 133750.]
 [ 88500. 105000. 122500.]]

Pretty Percentile Table:



,25th,50th,75th
Small,92500.0,110000.0,132500.0
Medium,88000.0,106000.0,133750.0
Large,88500.0,105000.0,122500.0


In [3]:
import numpy as np

remote_ratio = np.array([
    100, 0, 50, 100, 0, 50, 100, 0, 50, 100,
    0, 50, 100, 0, 50, 100, 0, 50, 100, 0
])

salary_in_usd = np.array([
    70000, 80000, 75000, 77000, 85000, 90000, 95000, 97000, 100000,
    105000, 110000, 115000, 120000, 125000, 130000, 135000, 140000,
    145000, 150000, 155000
])

fully_remote_salaries = salary_in_usd[remote_ratio == 100]
hybrid_salaries = salary_in_usd[remote_ratio == 50]
onsite_salaries = salary_in_usd[remote_ratio == 0]

avg_fully_remote = np.mean(fully_remote_salaries)
avg_hybrid = np.mean(hybrid_salaries)
avg_onsite = np.mean(onsite_salaries)

print("Average Salaries:")
print(f"Fully Remote (100%): ${avg_fully_remote:.2f}")
print(f"Hybrid (50%): ${avg_hybrid:.2f}")
print(f"On-site (0%): ${avg_onsite:.2f}")

mean_salary = np.mean(salary_in_usd)
std_salary = np.std(salary_in_usd)
normalized_salaries = (salary_in_usd - mean_salary) / std_salary

correlation = np.corrcoef(remote_ratio, salary_in_usd)[0,1]

print(f"\nCorrelation between remote work ratio and salary: {correlation:.3f}")


Average Salaries:
Fully Remote (100%): $107428.57
Hybrid (50%): $109166.67
On-site (0%): $113142.86

Correlation between remote work ratio and salary: -0.092
